import type { Problem } from '../types'

export const PROBLEMS: Problem[] = [
  // ── 데이터 조회
  {
    id: 'p-select-1',
    lessonId: 'select',
    title: '상품 이름과 가격',
    difficulty: 1,
    description: '`products` 테이블에서 **상품 이름(name)과 가격(price)** 두 열만 조회하세요.',
    answerSql: 'SELECT name, price FROM products',
    hint: '필요한 열만 SELECT 뒤에 쉼표로 나열합니다.',
  },
  {
    id: 'p-select-2',
    lessonId: 'select',
    title: '카테고리 목록',
    difficulty: 1,
    description: '`products` 에 어떤 **카테고리(category)** 가 있는지 중복 없이 한 열로 조회하세요.',
    answerSql: 'SELECT DISTINCT category FROM products',
    hint: 'DISTINCT 는 SELECT 바로 뒤에 씁니다.',
  },
  {
    id: 'p-select-3',
    lessonId: 'select',
    title: '할인가 계산',
    difficulty: 1,
    description: '`products` 에서 **이름(name)** 과 **20% 할인한 가격** 을 조회하세요. 할인가는 `price * 0.8` 입니다.',
    answerSql: 'SELECT name, price * 0.8 FROM products',
    hint: '열끼리 계산한 식을 SELECT 에 그대로 적을 수 있습니다.',
  },
  {
    id: 'p-where-1',
    lessonId: 'where',
    title: '5만원 이상 전자기기',
    difficulty: 1,
    description: '`products` 에서 카테고리가 **전자기기** 이고 가격이 **50,000 이상** 인 상품의 **이름(name), 가격(price)** 을 조회하세요.',
    answerSql: "SELECT name, price FROM products WHERE category = '전자기기' AND price >= 50000",
    hint: '두 조건을 AND 로 잇습니다. 문자열은 작은따옴표로.',
  },
  {
    id: 'p-where-2',
    lessonId: 'where',
    title: '서울 또는 부산 고객',
    difficulty: 1,
    description: '`customers` 에서 도시(city)가 **서울 또는 부산** 인 고객의 **이름(name), 도시(city)** 를 조회하세요.',
    answerSql: "SELECT name, city FROM customers WHERE city IN ('서울', '부산')",
    hint: 'IN (...) 또는 OR 를 씁니다.',
  },
  {
    id: 'p-where-3',
    lessonId: 'where',
    title: '이름으로 찾기',
    difficulty: 2,
    description: '`products` 에서 이름에 **"용"** 이 들어가는 상품의 **이름(name)** 을 조회하세요. (예: 사무용 의자, 복사용지)',
    answerSql: "SELECT name FROM products WHERE name LIKE '%용%'",
    hint: 'LIKE 와 % 를 씁니다. 앞뒤 어디든 올 수 있으면 양쪽에 %.',
  },
  {
    id: 'p-order-1',
    lessonId: 'order-limit',
    title: '가장 비싼 상품 3개',
    difficulty: 1,
    orderMatters: true,
    description: '`products` 에서 **가장 비싼 상품 3개** 의 **이름(name), 가격(price)** 을 비싼 순서대로 조회하세요.',
    answerSql: 'SELECT name, price FROM products ORDER BY price DESC LIMIT 3',
    hint: 'ORDER BY ... DESC 뒤에 LIMIT.',
  },
  {
    id: 'p-order-2',
    lessonId: 'order-limit',
    title: '오래된 고객 5명',
    difficulty: 1,
    orderMatters: true,
    description: '`customers` 에서 **가입일(joined_at)이 가장 오래된 5명** 의 **이름(name), 가입일(joined_at)** 을 가입일 순으로 조회하세요.',
    answerSql: 'SELECT name, joined_at FROM customers ORDER BY joined_at LIMIT 5',
    hint: '날짜 문자열은 ISO 형식이라 그냥 정렬하면 됩니다. 오름차순이 기본.',
  },
  {
    id: 'p-null-1',
    lessonId: 'null',
    title: '성적이 없는 수강',
    difficulty: 1,
    description: '`enrollments` 에서 **아직 성적(score)이 없는 수강의 수** 를 한 값으로 조회하세요.',
    answerSql: 'SELECT count(*) FROM enrollments WHERE score IS NULL',
    hint: '= NULL 은 안 됩니다. IS NULL.',
  },
  {
    id: 'p-null-2',
    lessonId: 'null',
    title: 'NULL 을 0 으로',
    difficulty: 2,
    description: '`enrollments` 에서 2024-2 학기 수강의 **수강 번호(id)** 와 **성적** 을 조회하되, 성적이 NULL 이면 **0** 으로 보여 주세요.',
    answerSql: "SELECT id, coalesce(score, 0) FROM enrollments WHERE semester = '2024-2'",
    hint: 'COALESCE(score, 0) 또는 IFNULL.',
  },
  {
    id: 'p-func-1',
    lessonId: 'functions',
    title: '가입 연도',
    difficulty: 2,
    description: '`customers` 에서 **이름(name)** 과 **가입 연도(4자리)** 를 조회하세요. 가입일은 `YYYY-MM-DD` 형식입니다.',
    answerSql: 'SELECT name, substr(joined_at, 1, 4) FROM customers',
    hint: "substr(joined_at, 1, 4) 또는 strftime('%Y', joined_at).",
  },
  {
    id: 'p-case-1',
    lessonId: 'case',
    title: '가격대 분류',
    difficulty: 2,
    description: '`products` 에서 **이름(name)** 과 **가격대** 를 조회하세요. 가격대는 100,000 이상이면 `고가`, 30,000 이상이면 `중가`, 나머지는 `저가` 입니다.',
    answerSql: "SELECT name, CASE WHEN price >= 100000 THEN '고가' WHEN price >= 30000 THEN '중가' ELSE '저가' END FROM products",
    hint: 'CASE WHEN ... THEN ... ELSE ... END. 큰 값부터 검사합니다.',
  },
  // ── 집계와 그룹
  {
    id: 'p-agg-1',
    lessonId: 'aggregate-functions',
    title: '상품 가격 통계',
    difficulty: 1,
    description: '`products` 전체의 **평균 가격, 최고 가격, 최저 가격** 을 한 행 세 열로 조회하세요.',
    answerSql: 'SELECT avg(price), max(price), min(price) FROM products',
    hint: 'avg, max, min 을 한 SELECT 에 나란히.',
  },
  {
    id: 'p-agg-2',
    lessonId: 'aggregate-functions',
    title: '배송완료 주문 수',
    difficulty: 1,
    description: '`orders` 에서 상태(status)가 **delivered** 인 주문이 몇 건인지 한 값으로 조회하세요.',
    answerSql: "SELECT count(*) FROM orders WHERE status = 'delivered'",
    hint: 'WHERE 로 거른 뒤 count(*).',
  },
  {
    id: 'p-group-1',
    lessonId: 'group-by',
    title: '카테고리별 상품 수',
    difficulty: 1,
    description: '`products` 를 **카테고리(category)별** 로 묶어 **카테고리, 상품 수** 를 조회하세요.',
    answerSql: 'SELECT category, count(*) FROM products GROUP BY category',
    hint: 'GROUP BY category 와 count(*).',
  },
  {
    id: 'p-group-2',
    lessonId: 'group-by',
    title: '3건 이상 주문한 고객',
    difficulty: 2,
    description: '`orders` 에서 **주문이 3건 이상인 고객의 customer_id 와 주문 수** 를 조회하세요.',
    answerSql: 'SELECT customer_id, count(*) FROM orders GROUP BY customer_id HAVING count(*) >= 3',
    hint: '집계 결과 조건은 WHERE 가 아니라 HAVING.',
  },
  {
    id: 'p-group-3',
    lessonId: 'group-by',
    title: '전공별 평균 성적',
    difficulty: 3,
    description:
      '`students` 와 `enrollments` 를 이용해 **전공(major)별 평균 성적** 을 조회하세요. 열은 **전공, 평균(소수 첫째 자리까지 반올림)** 두 개입니다. 성적이 NULL 인 수강은 평균에서 빠집니다.',
    answerSql: 'SELECT s.major, round(avg(e.score), 1) FROM students s JOIN enrollments e ON e.student_id = s.id GROUP BY s.major',
    hint: 'JOIN 뒤 GROUP BY s.major. avg 는 NULL 을 알아서 무시합니다. round(x, 1).',
  },
  // ── 여러 테이블
  {
    id: 'p-join-1',
    lessonId: 'join',
    title: '주문과 고객 이름',
    difficulty: 2,
    description: '**배송완료(delivered)** 된 주문의 **주문 번호(orders.id), 고객 이름(customers.name), 주문일(ordered_at)** 을 조회하세요.',
    answerSql: "SELECT o.id, c.name, o.ordered_at FROM orders o JOIN customers c ON c.id = o.customer_id WHERE o.status = 'delivered'",
    hint: 'orders 와 customers 를 customer_id = id 로 JOIN.',
  },
  {
    id: 'p-join-2',
    lessonId: 'join',
    title: '고객별 총 구매액 상위 5명',
    difficulty: 3,
    orderMatters: true,
    description: '취소되지 않은 주문 기준으로 **고객 이름과 총 구매액(수량 × 단가의 합)** 을 구해, **구매액이 큰 순서로 5명** 조회하세요.',
    answerSql:
      "SELECT c.name, sum(oi.quantity * oi.unit_price) AS total FROM customers c JOIN orders o ON o.customer_id = c.id JOIN order_items oi ON oi.order_id = o.id WHERE o.status <> 'cancelled' GROUP BY c.id ORDER BY total DESC LIMIT 5",
    hint: '세 테이블 JOIN → WHERE status <> cancelled → GROUP BY 고객 → ORDER BY 합계 DESC LIMIT 5.',
  },
  {
    id: 'p-leftjoin-1',
    lessonId: 'left-join',
    title: '주문 없는 고객',
    difficulty: 2,
    description: '**한 번도 주문하지 않은 고객의 이름(name)** 을 조회하세요.',
    answerSql: 'SELECT c.name FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE o.id IS NULL',
    hint: 'LEFT JOIN 뒤 오른쪽 열이 IS NULL 인 행. NOT EXISTS 로도 됩니다.',
  },
  {
    id: 'p-leftjoin-2',
    lessonId: 'left-join',
    title: '고객별 주문 수 (0 포함)',
    difficulty: 2,
    description: '모든 고객에 대해 **이름(name)과 주문 수** 를 조회하세요. 주문이 없는 고객은 **0** 으로 나와야 합니다.',
    answerSql: 'SELECT c.name, count(o.id) FROM customers c LEFT JOIN orders o ON o.customer_id = c.id GROUP BY c.id',
    hint: 'LEFT JOIN 과 count(o.id). count(*) 를 쓰면 0 이 아니라 1 이 나옵니다.',
  },
  {
    id: 'p-sub-1',
    lessonId: 'subquery',
    title: '평균보다 비싼 상품',
    difficulty: 2,
    description: '`products` 에서 **전체 평균 가격보다 비싼 상품의 이름(name), 가격(price)** 을 조회하세요.',
    answerSql: 'SELECT name, price FROM products WHERE price > (SELECT avg(price) FROM products)',
    hint: 'WHERE price > (SELECT avg(price) FROM products).',
  },
  {
    id: 'p-sub-2',
    lessonId: 'subquery',
    title: '도서를 산 고객',
    difficulty: 3,
    description: '**도서 카테고리 상품을 한 번이라도 주문한 고객의 이름(name)** 을 중복 없이 조회하세요.',
    answerSql:
      "SELECT DISTINCT c.name FROM customers c WHERE c.id IN (SELECT o.customer_id FROM orders o JOIN order_items oi ON oi.order_id = o.id JOIN products p ON p.id = oi.product_id WHERE p.category = '도서')",
    hint: 'IN 서브쿼리 안에서 orders → order_items → products 를 JOIN 해 customer_id 목록을 만듭니다.',
  },
  {
    id: 'p-union-1',
    lessonId: 'union',
    title: '두 학기 모두 수강한 학생',
    difficulty: 2,
    description: '`enrollments` 에서 **2024-1 학기와 2024-2 학기에 모두 수강한 학생의 student_id** 를 조회하세요.',
    answerSql: "SELECT student_id FROM enrollments WHERE semester = '2024-1' INTERSECT SELECT student_id FROM enrollments WHERE semester = '2024-2'",
    hint: 'INTERSECT. 또는 GROUP BY student_id HAVING count(DISTINCT semester) = 2.',
  },
  // ── 한 걸음 더
  {
    id: 'p-window-1',
    lessonId: 'window-functions',
    title: '부서별 최고 연봉자',
    difficulty: 3,
    description: '`employees` 와 `departments` 에서 **부서별로 연봉이 가장 높은 직원** 의 **부서 이름, 직원 이름, 연봉** 을 조회하세요. 부서 미배정 직원은 제외합니다.',
    answerSql:
      'WITH r AS (SELECT d.name AS dept, e.name, e.salary, row_number() OVER (PARTITION BY e.department_id ORDER BY e.salary DESC) AS rn FROM employees e JOIN departments d ON d.id = e.department_id) SELECT dept, name, salary FROM r WHERE rn = 1',
    hint: 'row_number() OVER (PARTITION BY 부서 ORDER BY 연봉 DESC) 를 WITH 로 감싸고 rn = 1.',
  },
  {
    id: 'p-self-1',
    lessonId: 'self-join-recursive',
    title: '직원과 상사',
    difficulty: 2,
    description: '`employees` 에서 **모든 직원의 이름과 직속 상사 이름** 을 조회하세요. 상사가 없는 대표는 상사 이름이 **NULL** 로 나와야 합니다.',
    answerSql: 'SELECT e.name, m.name FROM employees e LEFT JOIN employees m ON m.id = e.manager_id',
    hint: '같은 테이블을 별칭 두 개로 LEFT JOIN.',
  },
  {
    id: 'p-self-2',
    lessonId: 'self-join-recursive',
    title: '개발팀장 아래 전체 인원',
    difficulty: 3,
    description: '**김개발** 의 직속·간접 부하 직원이 모두 몇 명인지(본인 제외) 한 값으로 조회하세요.',
    answerSql:
      "WITH RECURSIVE t(id) AS (SELECT id FROM employees WHERE name = '김개발' UNION ALL SELECT e.id FROM employees e JOIN t ON e.manager_id = t.id) SELECT count(*) - 1 FROM t",
    hint: 'WITH RECURSIVE 로 김개발부터 시작해 manager_id 를 따라 내려갑니다.',
  },
]
